name: கிளிமூக்கு சோதனைகள்

on: [ workflow_call ]

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ulavi-sodanaikal:
    name: கிளிமூக்கு உலாவி சோதனைகள்
    runs-on: ubuntu-latest
    steps:
      - name: Préparation de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Installer pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: latest

      - name: Ouvrir la branche
        uses: actions/checkout@v4

      - name: Installer
        run: pnpm install

      - name: Vérifier les tests
        run: pnpm சோதனை:உலாவி

      - name: Envoyer couverure à Codecov
        uses: codecov/codecov-action@v4
  kannu-sodanaikal:
    name: கிளிமூக்கு கணு சோதனைகள்
    runs-on: ubuntu-latest
    steps:
      - name: Préparation de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Installer pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: latest

      - name: Ouvrir la branche
        uses: actions/checkout@v4

      - name: Installer
        run: pnpm install

      - name: Vérifier les tests
        run: pnpm சோதனை:கணு

      - name: Envoyer couverure à Codecov
        uses: codecov/codecov-action@v4
